### ISSUE TITLE
Variating minimum bot.y

### ISSUE THREAD

**Issue by raccoon19** [leMaik/EduCraft#17]
The minimum bot.y value varies between each sandbox. In the first box the minimum is 1. In sandbox2 and sandbox3 it is 0. Besides in sandbox3 bot.y=0 is not on bedrock.

**Comment by leMaik** [comment]
The bot location should be relative to the environment. I'll look into that. Note that bot.y == 0 should not necessarily mean that it is at bedrock but only that it is at the bottom-most location of the sandbox.

**Comment by leMaik** [comment]
The bot.y value is correct but my demo environments have strange settings. I'll fix that soon and close this as it turns out to not really be an EduCraft bug.
