### ISSUE TITLE
Survival mode

### ISSUE THREAD

**Issue by leMaik** [leMaik/EduCraft#3]
LordSim0n [suggested](https://forum.craften.de/threads/lemaiks-experimentier-server-und-educraft.358/#post-4012) a survival mode. In this mode, the bot can only place blocks that were previously mined.

**Comment by AndriesTheBest** [comment]
Wow, that is awesome, pls do it! That would be cool!!

**Comment by leMaik** [comment]
This is now implemented. Blocks drop as if they were mined with silk touch. Sheep drop two wool blocks when sheared.

I also added a new validator so that environments can check the bot's inventory.

**Comment by AndriesTheBest** [comment]
Awesome I will look at it soon!
